# Add account credentials and API keys here.
# See http://railsapps.github.com/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#

ADMIN_FIRST_NAME: First
ADMIN_LAST_NAME: User
ADMIN_EMAIL: 
ADMIN_PASSWORD: 
ROLES: "['admin', 'starter', 'professional', 'business']"

MAIL_DOMAIN: 
MAIL_FROM_ADDRESS: 

MAILGUN_API_KEY: 
MAILGUN_PUBLIC_API_KEY: 
MAILGUN_API_URL: 

MAILGUN_SMTP_PORT: 
MAILGUN_SMTP_SERVER: 
MAILGUN_SMTP_LOGIN: 
MAILGUN_SMTP_PASSWORD: 

TWILIO_ACCOUNT_SID: 
TWILIO_AUTH_TOKEN: 
TWILIO_PHONE_NUMBER: 
TWILIO_APPLICATION_SID: 

TZ: 'Europe/Berlin'

DOMAIN_NAME: 
DOMAIN_PROTOCOL: https

staging:
  MAIL_DOMAIN: 
  DOMAIN_NAME: 
  DOMAIN_PROTOCOL: https

production:
  MAIL_DOMAIN: 
  DOMAIN_NAME: 
  DOMAIN_PROTOCOL: https
